apiVersion: v1
kind: Service
metadata:
  name: uv-service
spec:
  type: NodePort
  selector:
    type: back-end
    tier: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50009
